/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111752-g80fdf51b8f-20230813"
#endif /* AVUTIL_FFVERSION_H */
